<a href="https://colab.research.google.com/github/Muskankapila016/Machine-Learning/blob/main/Assignment_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Asssignment 1(using NUMPY)

In [1]:
#importing library numpy
import numpy as np 

Q1: Questions on Basic NumPy Array 

In [ ]:
a=np.array([1,2,3,4,5,6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

In [ ]:
print(f"After flipping >>{np.flip(a)}")

After flipping >>[6 5 4 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two 
NumPy in-built methods

In [ ]:
b=np.array([[1,2,3],[2,4,5],[1,2,3]])

In [ ]:
b.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

c) Compare the following numpy arrays: 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


In [ ]:
#comparing 2 arrays are equal or not
np.array_equal(arr1,arr2)

True

In [ ]:
arr1.size

4

(d) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [ ]:
 x = np.array([1,2,3,4,5,1,2,1,1,1])
 y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [ ]:
value=np.bincount(x).argmax()
loc=np.where(x==value)
print(f"Most frequent ocuuring value is :{value} and its indices are:{loc}")

Most frequent ocuuring value is :1 and its indices are:(array([0, 5, 7, 8, 9]),)


In [ ]:
value=np.bincount(y).argmax()
loc=np.where(y==value)
print(f"Most frequent ocuuring value is :{value} and its indices are:{loc}")

Most frequent ocuuring value is :1 and its indices are:(array([0, 1, 2]),)


e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
i. Sum of all elements 
ii. Sum of all elements row-wise 
iii. Sum of all elements column-wise 

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [ ]:
gfg

matrix([[ 4,  1,  9],
        [12,  3,  1],
        [ 4,  5,  6]])

In [ ]:
g = gfg.sum()

In [ ]:
g

45

In [ ]:
g = gfg.sum(axis=1)#columm wise sum

In [ ]:
g

matrix([[14],
        [16],
        [15]])

In [ ]:
g = gfg.sum(axis=0)#row wise sum

In [ ]:
g

matrix([[20,  9, 16]])

(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements 
ii. Eigen values of matrix 
iii. Eigen vectors of matrix 
iv. Inverse of matrix 
v. Determinant of matrix

In [ ]:
 n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
 n_array

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [ ]:
trace = np.trace(n_array)
trace

176

In [ ]:
# finding eigenvalues and eigenvectors
values, vectors = np.linalg.eig(n_array)
  
# printing eigen values
print("Printing the Eigen values of the given square array:\n",values)
  
# printing eigen vectors
print("Printing eigenvectors of the given square array:\n",vectors)

Printing the Eigen values of the given square array:
 [98.16835147 28.097044   49.73460452]
Printing Right eigenvectors of the given square array:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
# Calculating the inverse of the matrix
print(np.linalg.inv(n_array))

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 3X3 matrix:")
print(det)


Determinant of given 3X3 matrix:
137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy: 
i. p = [[1, 2], [2, 3]] q = [[4, 5], [6, 7]] 
ii. p = [[1, 2], [2, 3], [4, 5]] q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]] 

In [ ]:
# This will return dot product
res = np.dot(p,q)
# print resulted matrix
print(res)

[[16 19]
 [26 31]]


In [ ]:
# Covariance matrix
print("\nCovariance matrix of the said arrays:\n",np.cov(p, q))


Covariance matrix of the said arrays:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
# This will return dot product
res = np.dot(p,q)
# print resulted matrix
print(res)

[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
# Covariance matrix(shape of both the matrix should be same)
print("\nCovariance matrix of the said arrays:\n",np.cov(p, q))

(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
find inner, outer and cartesian product?


In [ ]:
a = np.array([[2, 3, 4], [3, 2, 9]])
b = np.array([[1, 5, 0], [5, 10, 3]])

In [ ]:
# Inner Product of Vectors
print("\nInner product of a and b =")
print(np.inner(a, b))


Inner product of a and b =
[[17 52]
 [13 62]]


In [ ]:
# Outer product of vectors 
print("\nOuter product of vectors a and b =")
print(np.outer(a, b))


Outer product of vectors a and b =
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
#cartesian product
result =  np.cross(a,b)
print(result)

[[-20   4   7]
 [-84  36  20]]


Q2: Based on NumPy Mathematics and Statistics 


(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value 

In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

In [ ]:
array

array([[ 1, -2,  3],
       [-4,  5, -6]])

In [ ]:
print(f"Element wise absolute value is:{np.absolute(array)}")

Element wise absolute value is:[[1 2 3]
 [4 5 6]]


ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
row

In [ ]:
arr= np.array([[1, -2, 3],[-4, 5, -6]])

In [ ]:
arr=arr.flatten()

In [ ]:
# Percentile of the flattened array
# Percentile along the axis = 0
print("\n50th Percentile of arr, axis = 0 : ",np.percentile(arr, 50, axis =0))
print("\n25th Percentile of arr, axis = 0 : ",np.percentile(arr, 25, axis =0))
print("\n75th Percentile of arr, axis = 0 : ",np.percentile(arr, 75, axis =0))


50th Percentile of arr, axis = 0 :  -0.5

25th Percentile of arr, axis = 0 :  -3.5

75th Percentile of arr, axis = 0 :  2.5


In [ ]:
# Percentile of the flattened array
# Percentile along the axis = 1(row wise)
print("\n50th Percentile of arr, axis = 1 : ",np.percentile(arr, 50, axis =1))
print("\n25th Percentile of arr, axis = 1 : ",np.percentile(arr, 25, axis =1))
print("\n75th Percentile of arr, axis = 1 : ",np.percentile(arr, 75, axis =1))

iii. Mean, Median and Standard Deviation of flattened array, of each column, and 
each row

In [5]:
arr= np.array([[1, -2, 3],[-4, 5, -6]])

In [7]:
#calculate standard deviation
print(f"standard deviation along x axis {np.std(arr, axis=1)}")
print("-----------------")
print(f"standard deviation along y axis {np.std(arr, axis=0)}")

standard deviation along x axis [2.05480467 4.78423336]
-----------------
standard deviation along y axis [2.5 3.5 4.5]


In [ ]:
#to calculate mean
print(np.mean(arr, axis=0))
print("-----------------------")
print(np.mean(arr, axis=1))

[-1.5  1.5 -1.5]
-----------------------
[ 0.66666667 -1.66666667]


In [ ]:
#to calculate median
print(np.median(arr, axis=0))
print("-----------------------")
print(np.median(arr, axis=1))


[-1.5  1.5 -1.5]
-----------------------
[ 1. -4.]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
and truncated value, rounded values

In [ ]:
arr = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

In [ ]:
# Get floor value
a = np.floor(arr)
print(a)

[-2. -2. -1.  0.  1.  1.  3.]


In [ ]:
# Get ceil value
a = np.ceil(arr)
print(a)

[-1. -1. -0.  1.  2.  2.  3.]


In [ ]:
# Get truncate value
a = np.trunc(arr)
print(a)

[-1. -1. -0.  0.  1.  1.  3.]


Q3: Based on Searching and Sorting 

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 

i. Sorted array 
ii. Indices of sorted array 
iii. 4 smallest elements 
iv. 5 largest elements

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

In [ ]:
c = (np.sort(array))
print(c)

[ 10  16  16  52  54  62 453]


In [ ]:
i = np.argsort(array)
print("Indices of the sorted elements of a given array:")
print(i)

Indices of the sorted elements of a given array:
[0 3 4 1 5 2 6]


In [ ]:
# k smallest number of array
k=4
print(k, "smallest elements of the array")
print(c[:k])

4 smallest elements of the array
[10 16 16 52]


In [ ]:
# find n largest value
n=5
rslt = c[-n : ]
  
# show the output
print(f"{n} largest value:", rslt)

5 largest value: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 

i. Integer elements only 
ii. Float elements only

In [10]:
def isInt(num):
    return np.equal(np.mod(num, 1),0)
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
for num in arr:
    if isInt(num):
        print(num, "is an integer")

1.0 is an integer
2.0 is an integer
3.0 is an integer
2.0 is an integer


In [11]:
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
for i in arr:
    if type(i)==float:
        print(i, "is a float element")

Q4: 
(a) Write a function named img_to_array(path) that reads an image from a specified path and 
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
images) 
(b) Load the saved file into jupyter notebook? 

In [2]:
!pip install Pillow
from PIL import Image

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
def img_to_array(path):
  image = Image.open(path)
  data = np.asarray(image)
  with open("file.txt","w") as file:
    file.write(f"{data}")

print("Grey scale image")
img_to_array('/content/machine-learning.jpg')
print("RGB image")
img_to_array('/content/machine-learning.jpg')

Grey scale image
RGB image
